const promptCAH = [
    `${response1} + ${response2} = ${response3}.`,
    `${response1} is a slippery slope that leads to ${response2}.`,
    `${response1} would be woefully incomplete without ${response2}.`,
    `${response1}: good to the last drop.`,
    `${response1}: kid tested, mother approved.`,
    `${response1}: kid-tested, mother-approved.`,
    `${response1}: Once you pop, the fun don't stop!`,
    `${response1}? Jim'll fix it!`,
    `${response1}? There's an app for that.`,
    `${response1}? Yeah, nah.`,
    `${response1}. Awesome in theory, kind of a mess in practice.`,
    `${response1}. Betcha can't have just one!`,
    `${response1}. High five, bro.`,
    `${response1}. It's a trap!`,
    `${response1}. That was so metal.`,
    `${response1}. That's how I want to die.`,
    `${response1}. That's why mums go to Iceland.`,
    `Do NOT go here! Found ${response1} in my Kung Pao chicken! `,
    `50% of all marriages end in ${response1}.`,
    `A recent laboratory study shows that undergraduates have 50% less sex after being exposed to ${response1}.`,
    `A remarkable new study has shown that chimps have evolved their own primitive version of ${response1}.`,
    `A romantic candlelit dinner would be incomplete without ${response1}.`,
    `A romantic, candlelit dinner would be incomplete without ${response1}.`,
    `A successful job interview begins with a firm handshake and ends with ${response1}.`,
    `ABC presents: "${response1}: The Story of ${response2}."`,
    `After months of practice with ${response1}, I think I’m finally ready for ${response2}.`,
    `And the Academy Award for ${response1} goes to ${response2}.`,
    `CTV presents "${response1}: the Story of ${response2}."`,
    `Dear Sir or Madam, We regret to inform you that the Office of ${response1} has denied your request for ${response2}.`,
    `For my next trick, I will pull ${response1} out of ${response2}.`,
    `Having problems with ${response1}? Try ${response2}!`,
    `I never truly understood ${response1} until I encountered ${response2}.`,
    `I spent my whole life working toward ${response1}, only to have it ruined by ${response2}.`,
    `In a world ravaged by ${response1} our only solace is ${response2}.`,
    `In his new summer comedy, Rob Schneider is ${response1} trapped in the body of ${response2}.`,
    `In M. Night Shyamalan's new movie, Bruce Willis discovers that ${response1} had really been ${response2} all along.`,
    `Introducing the amazing superhero/sidekick duo! It's ${response1} and ${response2}!`,
    `Lifetime® presents ${response1}: the Story of ${response2}.`,
    `Lifetime® presents "${response1}: the Story of ${response2}."`,
    `My mom freaked out when she looked at my browser history and found ${response1}.com/${response2}.`,
    `My plan for world domination begins with ${response1}.`,
    `Rumor has it that Vladimir Putin's favorite dish is ${response1} stuffed with ${response2}.`,
    `"Step 1: ${response1}. Step 2: ${response2}. Step 3: Profit."`,
    `That's right, I killed ${response1}. How, you ask? ${response2}.`,
    `They said we were crazy. They said we couldn't put ${response1} inside of ${response2}. They were wrong.`,
    `What's the next superhero/sidekick duo?`,
    `When I was tripping on acid, ${response1} turned into ${response2}.`,
    `When you get right down to it, ${response1} is just ${response2}.`,
    `With enough time and pressure, ${response1} will turn into ${response2}.`,
    `After eight years in the White House, how is Obama finally letting loose?`,
    `After four platinum albums and three Grammys, it's time to get back to my roots, to what inspired me to make music in the first place: ______.`,
    `After Hurricane Katrina, Sean Penn brought ______ to all the people of New Orleans.`,
    `After Hurricane Katrina, Sean Penn brought ______ to the people of New Orleans.`,
    `After the earthquake, Sean Penn brought ______ to the people of Haiti.`,
    `Air Canada guidelines now prohibit ______ on airplanes.`,
    `Airport security guidelines now prohibit ______ on airplanes.`,
    `Alternative medicine is now embracing the curative powers of ______.`,
    `And the BAFTA for ______ goes to ______. `,
    `And what did you bring for show and tell?`,
    `Anthropologists have recently discovered a primitive tribe that worships ______.`,
    `Arby's: We Have ______.`,
    `"Are you thinking what I'm thinking, B1? I think I am, B2: it's ______ time!"`,
    `As my New Year's resolution, I vow to give up ______.`,
    `As the mom of five rambunctious boys, I'm no stranger to ______.`,
    `As the mum of five rambunctious boys, I'm no stranger to ______.`,
    `Betcha can't have just one!`,
    `BILLY MAYS HERE FOR ______.`,
    `Bravo's new reality show features eight washed-up celebrities living with ______.`,
    `Brought to you by Bud Light®, the Official Beer of ______.`,
    `Brought to you by Molson Canadian, the Official Beer of ______.`,
    `Brought to you by XXXX Gold, the Official Beer of ______.`,
    `But before I kill you, Mr. Bond, I must show you ______.`,
    `CBC presents "___: the Story of ___."`,
    `Channel 4 presents ______, the story of ______.`,
    `Channel 4 presents "______: the Story of ______."`,
    `Channel 5's new reality show features eight washed-up celebrities living with ______.`,
    `Channel 9 is pleased to present its new variety show, "Hey Hey It's ______."`,
    `Charades was ruined for me forever when my mom had to act out ______.`,
    `Check me out, yo! I call this dance move "______."`,
    `Click Here for ______!!!`,
    `Coming this season, Samuel Beckett's classic existential play: Waiting for ______.`,
    `Coming to Broadway this season, ______: The Musical.`,
    `Coming to the West End this year, ______: The Musical.`,
    `Crikey! I've never seen ______ like this before! Let's get a bit closer.`,
    `Daddy, why is mommy crying?`,
    `Daddy, why is mummy crying?`,
    `Dear Abby, I'm having some trouble with ______ and would like your advice.`,
    `Dear Agony Aunt, I'm having some trouble with ________ and I need your advice.`,
    `Dear Agony Aunt, I'm having some trouble with ________ and would like your advice.`,
    `Doctor, you've gone too far! The human body wasn't meant to withstand that amount of ______!`,
    `Dude, do not go in that bathroom. There's ______ in there.`,
    `Dude, do not go in that washroom. There's ______ in there.`,
    `Due to a PR fiasco, Walmart no longer offers ______.`,
    `During his childhood, Salvador Dali produced hundreds of paintings of ______.`,
    `During his midlife crisis, my dad got really into ______.`,
    `During Picasso's often-overlooked Brown Period, he produced hundreds of paintings of ______.`,
    `During sex, I like to think about ______.`,
    `Finally! A service that delivers ______ right to your door.`,
    `Fun tip! When your man asks you to go down on him, try surprising him with ______ instead.`,
    `Future historians will agree that ______ marked the beginning of America's decline.`,
    `"Here is the church, Here is the steeple, Open the doors, And there is ______."`,
    `Hey guys, welcome to Boston Pizza! Would you like to start the night off right with ______?`,
    `Hey guys, welcome to Chili's! Would you like to start the night off right with ______?`,
    `Hey guys, welcome to Sizzler! Would you like to start the night off right with ______?`,
    `Hey guys, welcome to TGI Fridays! Would you like to start the night off right with ______?`,
    `Hey guys, welcome to TGIF! Would you like to start the night off right with ______?`,
    `Hey Reddit! I'm ______. Ask me anything.`,
    `How am I maintaining my relationship status?`,
    `How did I lose my virginity?`,
    `I do not know with what weapons World War III will be fought, but World War IV will be fought with ______.`,
    `I drink to forget ______.`,
    `I get by with a little help from ______.`,
    `I got 99 problems but ______ ain't one.`,
    `I know when that hotline bling, that can only mean one thing: ______.`,
    `I learned the hard way that you can't cheer up a grieving friend with ______.`,
    `I wish I hadn't lost the instruction manual for ______.`,
    `I'm going on a cleanse this week. Nothing but kale juice and ______.`,
    `I'm Lebron James, and when I'm not slamming dunks, I love ______.`,
    `I'm no doctor, but I'm pretty sure what you're suffering from is called "______."`,
    `I'm sorry, Professor, but I couldn't complete my homework because of ______.`,
    `I'm sorry, Sir, but I couldn't complete my homework because of ______.`,
    `I’m not like the rest of you. I’m too rich and busy for ______.`,
    `If you can't be with the one you love, love ______.`,
    `IF you like ______, YOU MIGHT BE A REDNECK.`,
    `In 1,000 years, when paper money is a distant memory, how will we pay for goods and services?`,
    `In 1,000 years, when paper money is but a distant memory, ______ will be our currency.`,
    `In an attempt to reach a wider audience, the National Museum of Australia has opened an interactive exhibit on ______.`,
    `In an attempt to reach a wider audience, the Smithsonian Museum of Natural History has opened an interactive exhibit on ______.`,
    `In Australia, ______ is twice as big and twice as deadly.`,
    `In Belmarsh Prison, word is you can trade 200 cigarettes for ______.`,
    `In her latest feature-length film, Tracy Beaker struggles with ______ for the first time.`,
    `In his new self-produced album, Kanye West raps over the sounds of ______.`,
    `In L.A. County Jail, word is you can trade 200 cigarettes for ______.`,
    `In Michael Jackson's final moments, he thought about ______.`,
    `In Rome, there are whisperings that the Vatican has a secret room devoted to ______.`,
    `In the new Disney Channel Original Movie, Hannah Montana struggles with ______ for the first time.`,
    `In the seventh circle of Hell, sinners must endure ______ for all eternity.`,
    `In Wormwood Scrubs, word is you can trade 200 cigarettes for ______.`,
    `Instead of coal, Father Christmas now gives the bad children ______.`,
    `Instead of coal, Santa now gives the bad children ______.`,
    `Introducing X-Treme Baseball! It's like baseball, but with ______!`,
    `It’s a pity that kids these days are all getting involved with ______.`,
    `Just once, I'd like to hear you say "Thanks, Mom. Thanks for ______."`,
    `Just once, I'd like to hear you say "Thanks, Mum. Thanks for ______."`,
    `Just saw this upsetting video! Please retweet!! #stop______`,
    `Kids, I don't need drugs to get high. I'm high on ______.`,
    `Life for Aboriginal people was forever changed when the white man introduced them to ______.`,
    `Life for American Indians was forever changed when the White Man introduced them to ______.`,
    `Life was difficult for cavemen before ______.`,
    `Lovin’ you is easy ’cause you’re ______.`,
    `Major League Baseball has banned ______ for giving players an unfair advantage.`,
    `Mate, do not go in that bathroom. There's ______ in there.`,
    `Mate, do not go in that bathroom. There's ______ in there.`,
    `Mate, do not go in that toilet. There's ______ in there.`,
    `Maybe she's born with it. Maybe it's ______.`,
    `Men's Wearhouse: You're gonna like ______. I guarantee it.`,
    `Military historians remember Alexander the Great for his brilliant use of ______ against the Persians.`,
    `Money can’t buy me love, but it can buy me ______.`,
    `Mr. and Mrs. Diaz, we called you in because we're concerned about Cynthia. Are you aware that your daughter is ______?`,
    `MTV's new reality show features eight washed-up celebrities living with ______.`,
    `My fellow Americans: Before this decade is out, we will have ______ on the moon!`,
    `Next from J.K. Rowling: Harry Potter and the Chamber of ______.`,
    `Next from J.K. Rowling: Harry Potter and the Chamber of ______.`,
    `Next on ESPN2: The World Series of ______.`,
    `Next on Eurosport: The World Championship of _______.`,
    `Next on Nine's Wide World of Sports: The World Championship of ______.`,
    `Next on Sky Sports: The World Championship of ________.`,
    `Next on Sky Sports: The World Champsion of ________.`,
    `Next on TSN: The World Series of ______.`,
    `Next up on Channel 4: Ramsay's ______ Nightmares.`,
    `Nobody expects the Spanish Inquisition. Our chief weapons are fear, surprise, and ________.`,
    `Now at the National Museum of Australia: an interactive exhibit on ______.`,
    `Now at the Natural History Museum: an interactive exhibit on ______.`,
    `Now at the Royal Ontario Museum: an interactive exhibit on ______.`,
    `Now at the Smithsonian: an interactive exhibit on ______.`,
    `O Canada, we stand on guard for ______.`,
    `Oi! Show us ______!`,
    `Old MacDonald had ______. E-I-E-I-O.`,
    `Only two things in life are certain: death and ______.`,
    `Penalty! ______: that's 5 minutes in the box!`,
    `Qantas now prohibits ______ on airplanes.`,
    `Science will never explain ______.`,
    `Skidamarink a dink a dink, skidamarink a doo, I love ______.`,
    `Sorry everyone, I just ______.`,
    `Studies show that lab rats navigate mazes 50% faster after being exposed to ______.`,
    `TFL apologizes for the delay in train service due to ______.`,
    `The blind date was going horribly until we discovered our shared interest in ______.`,
    `The class field trip was completely ruined by ______.`,
    `The Five Stages of Grief: denial, anger, bargaining, ______, acceptance.`,
    `The healing process began when I joined a support group for victims of ______.`,
    `The Natural History Museum has just opened an interactive exhibit on ________.`,
    `The new Chevy Tahoe. With the power and space to take ______ everywhere you go.`,
    `The school excursion was completely ruined by ______.`,
    `The school field trip was completely ruined by ______.`,
    `The school trip was completely ruined by ______.`,
    `The secret to a lasting marriage is communication, communication, and ______.`,
    `The Smithsonian Museum of Natural History has just opened an interactive exhibit on ______.`,
    `The TFL apologizes for the delay in train service due to ________. `,
    `The theme for next year's Eurovision Song Contest is "We are ________."`,
    `The U.S. has begun airdropping ______ to the children of Afghanistan.`,
    `"This is the way the world ends, This is the way the world ends, Not with a bang but with ______."`,
    `This is your captain speaking. Fasten your seatbelts and prepare for ______.`,
    `This season at Steppenwolf, Samuel Beckett's classic existential play: Waitng for ______.`,
    `This season at the Old Vic, Samuel Beckett's classic existential play: Waiting for ______.`,
    `This season at the old Vic, Samuel Beckett's classic existential play: Waitng for ______.`,
    `This season at the Princess of Wales Theatre, Samuel Beckett's classic existential play: Waiting for ______.`,
    `This season at the Sydney Opera House, Samuel Beckett's classic existential play: Waiting for ______.`,
    `Today on Jerry Springer: "Help! My son is ______!"`,
    `Today on Maury: "Help! My son is ______!"`,
    `Today on The Jeremy Kyle Show: "Help! My son is ________!"`,
    `Tonight's top story: What you don't know about ________ could kill you.`,
    `TSA guidelines now prohibit ______ on airplanes.`,
    `Turns out that ______-Man was neither the hero we needed nor wanted.`,
    `Uh, hey guys, I know this was my idea, but I'm having serious doubts about ______.`,
    `UKIP: Putting ______ First!`,
    `War! What is it good for?`,
    `Well if you'll excuse me, gentlemen, I have a date with ______.`,
    `What am I giving up for Lent?`,
    `What are my parents hiding from me?`,
    `What are school administrators using to curb rampant teenage pregnancy?`,
    `What broke up the original Wiggles?`,
    `What brought the orgy to a grinding halt?`,
    `What did I bring back from Amsterdam?`,
    `What did I bring back from Bali?`,
    `What did I bring back from Mexico?`,
    `What did the US airdrop to the children of Afghanistan?`,
    `What did Vin Diesel eat for dinner?`,
    `What do old people smell like?`,
    `What does Dick Cheney prefer?`,
    `What don't you want to find in your Chinese food?`,
    `What don't you want to find in your doner kebab?`,
    `What don't you want to find in your Kung Pao chicken?`,
    `What don't you want to find in your Mongolian beef?`,
    `What ended my last relationship?`,
    `What gets better with age?`,
    `What gives me uncontrollable gas?`,
    `What has been making life difficult at the nudist colony?`,
    `What helps Barack Obama unwind?`,
    `What helps Obama unwind?`,
    `What is Batman's guilty pleasure?`,
    `What is George W. Bush thinking about right now?`,
    `What kept Margaret Thatcher busy in her waning years?`,
    `What left this stain on my couch?`,
    `What made my first kiss so awkward?`,
    `What makes life worth living?`,
    `What makes me a true blue Aussie?`,
    `What never fails to liven up the party?`,
    `What will always get you laid?`,
    `What will I bring back in time to convince people that I am a powerful wizard?`,
    `What would grandma find disturbing, yet oddly charming?`,
    `What's a girl's best friend?`,
    `What's my anti-drug?`,
    `What's my secret power?`,
    `What's Teach for America using to inspire inner city students to succeed?`,
    `What's that smell?`,
    `What's that sound?`,
    `What's the Canadian government using to inspire rural students to succeed?`,
    `What's the crustiest?`,
    `What's the most emo?`,
    `What's the new fad diet?`,
    `What's the next Happy Meal® toy?`,
    `What's there a ton of in heaven?`,
    `What's there a tonne of in heaven?`,
    `When all else fails, I can always masturbate to ______.`,
    `When I am a billionare, I shall erect a 20-meter statue to commemorate ______.`,
    `When I am a billionare, I shall erect a 20-metre statue to commemorate ______.`,
    `When I am a billionare, I shall erect a 50-foot statue to commemorate ______.`,
    `When I am President of the United States, I will create the Department of ______.`,
    `When I am President, I will create the Department of ______.`,
    `When I am Prime Minister of Canada, I will create the Department of ______.`,
    `When I am Prime Minister of Canada, I will create the Ministry of ______.`,
    `When I am Prime Minister of the United Kingdom, I will create the Ministry of ______.`,
    `When I am Prime Minister, I will create the Department of ______.`,
    `When I am Prime Minister, I will create the Ministry of ______.`,
    `When I pooped, what came out of my butt?`,
    `When I'm in prison, I'll have ______ smuggled in.`,
    `When Pharaoh remained unmoved, Moses called down a Plague of ______.`,
    `While the United States raced the Soviet Union to the moon, the Mexican government funneled millions of pesos into research on ______.`,
    `White people like ______.`,
    `Who stole the cookies from the cookie jar?`,
    `Why am I sticky?`,
    `Why can't I sleep at night?`,
    `Why do I hurt all over?`,
    `Your persistence is admirable, my dear Prince. But you cannot win my heart with ______ alone.`,
    `Do NOT go here! Found _____ in my fettuccine alfredo!`,
    `Hulu's new reality show features twelve hot singles living with ______.`,
    `In Jordan Peele's new thriller, a young family discovers that ______ had really been ______ all along.`,
    `Mitch McConnell can't cum without ______.`,
    `Why is Brett so sweaty?`,
]

const responseCAH = [
    `"Tweeting"`,
    `(I am doing Kegels right now)`,
    `10,000 Syrian refugees`,
    `100% Pure New Zealand`,
    `2 Girls 1 Cup`,
    `400 years of colonial atrocities`,
    `50 mg of Zoloft daily`,
    `50,000 volts straight to the nipples`,
    `72 virgins`,
    `8 oz of sweet Mexican black-tar heroin`,
    `A bag of magic beans`,
    `A balanced breakfast`,
    `A ball of earwax, semen, and toenail clippings`,
    `A big black dick`,
    `A big hoopla about nothing`,
    `A bird that shits human turds`,
    `A bit of slap and tickle`,
    `A bitch slap`,
    `A bleached arsehole`,
    `A bleached asshole`,
    `A Bop It™`,
    `A bowl of mayonnaise and human teeth`,
    `A brain tumor`,
    `A brain tumour`,
    `A bucket of fish heads`,
    `A can of whoop-ass`,
    `A caress of the inner thigh`,
    `A cartoon camel enjoying the smooth, refreshing taste of a cigarette`,
    `A cat video so cute that your eyes roll back and your spine slides out of your anus`,
    `A Chelsea smile `,
    `A Chinese tourist who wants something very badly but cannot communicate it`,
    `A clandestine butt scratch`,
    `A comprehensive understanding of the Irish backstop`,
    `A cooler full of organs`,
    `A cop who is also a dog`,
    `A crucifixion`,
    `A cute, fuzzy koala, but it has chlamydia`,
    `A death ray`,
    `A decent fucking Internet connection`,
    `A deep-rooted fear of the working class`,
    `A defective condom`,
    `A despondent Maple Leafs fan sitting all alone`,
    `A didgeridildo`,
    `A disappointing birthday party`,
    `A drive-by shooting`,
    `A fair go`,
    `A falcon with a cap on its head`,
    `A fanny fart`,
    `A fart so powerful that it wakes the giants from their thousand-year slumber`,
    `A fat bald man from the internet`,
    `A fetus`,
    `A five-litre goon bag`,
    `A Fleshlight`,
    `A Fleshlight®`,
    `A foetus`,
    `A foul mouth`,
    `A fuck-ton of almonds`,
    `A fuck-tonne of almonds`,
    `A gassy antelope`,
    `A general lack of purpose`,
    `A gentle caress of the inner thigh`,
    `A ginger's freckled ballsack`,
    `A Ginsters pasty and three cans of Monsters Energy`,
    `A good sniff`,
    `A good, strong gorilla`,
    `A gossamer stream of jizz that catches the light as it arcs through the morning air`,
    `A grande sugar-free iced soy caramel macchiato`,
    `A Gypsy curse`,
    `A hairless little shitstain named Callou`,
    `A Halal Snack Pack`,
    `A hen night in Slough`,
    `A homoerotic volleyball montage`,
    `A horde of Vikings`,
    `A hot mess`,
    `A Japanese toaster you can fuck`,
    `A Japanese whaling operation`,
    `A LAN party`,
    `A lifetime of sadness`,
    `A literal tornado of fire`,
    `A little boy who won't shut the fuck up about dinosaurs`,
    `A live studio audience`,
    `A look-see`,
    `A low standard of living`,
    `A mad cow`,
    `A madman who lives in a police box and kidnaps women`,
    `A man in yoga pants with a ponytail and feather earrings`,
    `A man on the brink of orgasm`,
    `A mating display`,
    `A meat raffle!`,
    `A Mexican`,
    `A micropenis`,
    `A micropig wearing a tiny raincoat and booties`,
    `A middle-aged man on roller skates`,
    `A mime having a stroke`,
    `A moment of silence`,
    `A monkey smoking a cigar`,
    `A mopey zoo lion`,
    `A much younger woman`,
    `A murder most foul`,
    `A neglected Tamagotchi™`,
    `A nice cup of tea`,
    `A pangender octopus who roams the cosmos in search of love`,
    `A piñata full of scorpions`,
    `A posh wank`,
    `A PowerPoint presentation`,
    `A pyramid of severed heads`,
    `A really cool hat`,
    `A robust mongoloid`,
    `A sad fat dragon with no friends`,
    `A sad handjob`,
    `A salad for men that's made of metal`,
    `A salty surprise`,
    `A sassy black woman`,
    `A sausage festival`,
    `A saxophone solo`,
    `A sea of troubles`,
    `A shark!`,
    `A sick burnout`,
    `A sick wombat`,
    `A sickly child-king`,
    `A six-point plan to stop the boats`,
    `A slab of VB and a pack of durries`,
    `A slightly salty toad in the hole`,
    `A slightly shittier parallel universe`,
    `A snapping turtle biting the tip of your penis`,
    `A sober Irishman who doesn't care for potatoes`,
    `A soggy Sao`,
    `A spastic nerd`,
    `A stingray barb through the chest`,
    `A stray pube`,
    `A subscription to Men's Fitness`,
    `A Super Soaker™ full of cat pee`,
    `A surprising amount of hair`,
    `A sweet spaceship`,
    `A thermonuclear detonation`,
    `A thousand Scottish warriors lifting their kilts in unison`,
    `A three-way with my wife and Shaquille O'Neal`,
    `A Tim Hortons franchise`,
    `A time travel paradox`,
    `A tiny horse`,
    `A tiny, gay guitar called a ukulele`,
    `A tribe of warrior women`,
    `A vagina that leads to another dimension`,
    `A vajazzled vagina`,
    `A vastly superior healthcare system`,
    `A vindaloo poo`,
    `A web of lies`,
    `A wheelchair death race`,
    `A white ethnostate`,
    `A white van man`,
    `A whole thing of butter`,
    `A windmill full of corpses`,
    `A wisecracking terrorist`,
    `A zesty breakfast burrito`,
    `Aaron Burr`,
    `Abstinence`,
    `Academy Award winner Meryl Streep`,
    `Accepting the way things are`,
    `Accidentally slipping yourself a roofie`,
    `Active listening`,
    `Actually getting shot, for real`,
    `Actually taking candy from a baby`,
    `Adderall™`,
    `Adult Friendfinder`,
    `Advice from a wise, old black man`,
    `African children`,
    `Agriculture`,
    `AIDS`,
    `Ainsley Harriott`,
    `Alcohol poisoning`,
    `Alcoholism`,
    `Alexandria Ocasio-Cortez`,
    `All four prongs of an echidna's penis`,
    `All my friends dying`,
    `All my gentleman suitors`,
    `All of this blood`,
    `All the dudes I've fucked`,
    `All-you-can-eat shrimp for $499`,
    `All-you-can-eat shrimp for $899`,
    `Altar boys`,
    `America`,
    `American Gladiators`,
    `Americanization`,
    `Amputees`,
    `An AK-47 assault rifle`,
    `An AK-47`,
    `An AR-15 assault rifle`,
    `An argument with Richard Dawkins`,
    `An army of skeletons`,
    `An ass disaster`,
    `An asymmetric boob job`,
    `An endless stream of diarrhea`,
    `An endless stream of diarrhoea`,
    `An entrenched class system`,
    `An erection that lasts longer than four hours`,
    `An Evening with Michael Buble`,
    `An evil man in evil clothes`,
    `An honest cop with nothing left to lose`,
    `An icepick lobotomy`,
    `An icy handjob from an Edmonton hooker`,
    `An M Night Shyamalan plot twist`,
    `An M16 assault rifle`,
    `An octopus giving seven handjobs and smoking a cigarette`,
    `An Oedipus complex`,
    `An old guy who's almost dead`,
    `An older woman who knows her way around the penis`,
    `An oversized lollipop`,
    `An ugly face`,
    `An unstoppable wave of fire ants`,
    `An unwanted pregnancy`,
    `An uppercut`,
    `Anal beads`,
    `Announcing that I am about to cum`,
    `Another goddamn vampire movie`,
    `Another shot of morphine`,
    `Anything that comes out of Prince Philip's mouth`,
    `Apologizing`,
    `Arnold Schwarzenegger`,
    `Asians who aren't good at math`,
    `Assless chaps`,
    `Attitude`,
    `Auschwitz`,
    `Australia`,
    `Authentic Mexican cuisine`,
    `Autocannibalism`,
    `AXE Body Spray`,
    `Badger culling`,
    `Ball-by-ball commentary from Richie Benaud`,
    `Balls`,
    `Bananas in Pajamas`,
    `Bananas`,
    `Barack Obama`,
    `Barely making $25,000 a year`,
    `Barely making £15,000 a year`,
    `Basic human decency`,
    `BATMAN!`,
    `BATMAN!!!`,
    `Battlefield amputations`,
    `Becoming a blueberry`,
    `Bees?`,
    `Being a busy adult with many important things to do`,
    `Being a dick to children`,
    `Being a dinosaur`,
    `Being a hideous beast that no one could love`,
    `Being a motherfucking sorcerer`,
    `Being a witch`,
    `Being a woman`,
    `Being able to talk to elephants`,
    `Being awesome at sex`,
    `Being black`,
    `Being Canadian`,
    `Being fabulous`,
    `Being fat and stupid`,
    `Being fucking stupid`,
    `Being hunted like a fox`,
    `Being marginalised`,
    `Being marginalized`,
    `Being on fire`,
    `Being rich`,
    `Being white`,
    `Benedict Cumberbatch`,
    `Bestiality`,
    `Bill Nye the Science Guy`,
    `Bingeing and purging`,
    `Bio-engineered assault turtles with acid breath`,
    `Bisexuality`,
    `Bitches`,
    `Black people`,
    `Bling`,
    `Blood farts`,
    `Blood, sweat, and tears`,
    `Blood, toil, tears, and sweat`,
    `Blowing my boyfriend so hard he shits`,
    `Blowing up Parliament`,
    `Boat people; half boat, half human`,
    `Bogies`,
    `Bond, James Bond`,
    `Bono`,
    `Booby-trapping the house to foil burglars`,
    `Boogers`,
    `Boris Johnson`,
    `Bosnian chicken farmers`,
    `Braiding three penises into a Curly Wurly`,
    `Braiding three penises into a licorice twist`,
    `Braiding three penises into a Twizzler`,
    `Breaking out into song and dance`,
    `Brexit`,
    `Britney Spears at 55`,
    `Brown people`,
    `Brutal austerity`,
    `Bubble butt bottom boys`,
    `Buckfast Tonic Wine`,
    `Bullshit`,
    `Burning down the White House`,
    `Buying the right pants to be cool`,
    `Canada: America's Hat`,
    `Canadian Netflix`,
    `Canned tuna with extra dolphin`,
    `Capturing Newt Gingrich and forcing him to dance in a monkey suit`,
    `Cardi B`,
    `Cards Against Humanity`,
    `Cashed-up bogans`,
    `Casually suggesting a threesome`,
    `Catapults`,
    `Centaurs`,
    `Chainsaws for hands`,
    `Charisma`,
    `Cheating in the Paralympics`,
    `Cheating in the Special Olympics`,
    `Cheeky bum sex`,
    `Chemical weapons`,
    `Child abuse`,
    `Child beauty pageants`,
    `Children on leashes`,
    `Chivalry`,
    `Christopher Walken`,
    `Chundering into a kangaroo's pouch`,
    `Chunks of dead backpacker`,
    `Chunks of dead hitchhiker`,
    `Chunks of dead prostitute`,
    `Chutzpah`,
    `Civilian casualties`,
    `Classist undertones`,
    `Clive Palmer's soft, shitty body`,
    `Clubbing baby seals`,
    `Coat hanger abortions`,
    `Cock`,
    `Cockfights`,
    `College`,
    `Committing suicide`,
    `Completely unwarranted confidence`,
    `Concealing a boner`,
    `Concealing an erection`,
    `Consensual sex`,
    `Consultants`,
    `Contagious face cancer`,
    `Converting to Islam`,
    `Cookie Monster devouring the Eucharist wafers`,
    `Copping a feel`,
    `Cottaging`,
    `Count Chocula`,
    `Court-ordered rehab`,
    `Covering myself with Parmesan cheese and chili flakes because I am pizza`,
    `Crazy hot cousin sex`,
    `Creed`,
    `Crippling debt`,
    `Crucifixion`,
    `Crumbs all over the bloody carpet`,
    `Crumbs all over the god damn carpet`,
    `Crumpets with the Queen`,
    `Crystal meth`,
    `Cuddling`,
    `Cumming deep inside my best bro`,
    `Cunnilingus`,
    `Customer service representatives`,
    `Cybernetic enhancements`,
    `Dad's funny balls`,
    `Daddies Brown Sauce`,
    `Daddies® Brown Sauce`,
    `Daddy issues`,
    `Daddy's belt`,
    `Daniel Radcliffe's delicious arsehole`,
    `Daniel Radcliffe's delicious asshole`,
    `Danny DeVito`,
    `Danny Dyer`,
    `Dark and mysterious forces beyond our control`,
    `Darth Vader`,
    `Date rape`,
    `Dave Matthews Band`,
    `David Bowie flying in on a tiger made of lightning`,
    `David Cameron`,
    `Dead babies`,
    `Dead birds everywhere`,
    `Dead parents`,
    `Deflowering the princess`,
    `Dental dams`,
    `Denying climate change`,
    `Destroying the evidence`,
    `Dick Cheney`,
    `Dick fingers`,
    `Dick pics`,
    `Dining with cardboard cutouts of the cast of Friends`,
    `Dirty nappies`,
    `Disco fever`,
    `Discovering he's a Tory`,
    `Diversity`,
    `Dogging`,
    `Doin' it in the butt`,
    `Doin' it up the bum`,
    `Doing a shit in Pudsey Bear's eyehole`,
    `Doing crimes`,
    `Doing it in the butt`,
    `Doing the right thing`,
    `Domino's™ Oreo™ Dessert Pizza`,
    `Don Cherry's wardrobe`,
    `Donald J Trump`,
    `Donald Trump`,
    `Double penetration`,
    `Douchebags on their iPhones`,
    `Dr Martin Luther King, Jr`,
    `Drinking alone`,
    `Drinking out of the toilet and eating garbage`,
    `Drinking out of the toilet and eating rubbish`,
    `Dropping a baby down the dunny`,
    `Dropping a chandelier on your enemies and riding the rope up`,
    `Drowning the kids in the bathtub`,
    `Druids`,
    `Drum circles`,
    `Dry heaving`,
    `Dwarf tossing`,
    `Dwayne "The Rock" Johnson`,
    `Dying alone and in pain`,
    `Dying of dysentery`,
    `Dying`,
    `Eastern European Turbo-Folk music`,
    `Eating a hard boiled egg out of my husband's arsehole`,
    `Eating a hard boiled egg out of my husband's asshole`,
    `Eating all of the cookies before the AIDS bake-sale`,
    `Eating an albino`,
    `Eating the last known bison`,
    `Eating too much of a lamp`,
    `Ecstasy`,
    `Ed Balls`,
    `Edible underpants`,
    `Edible underwear`,
    `Egging an MP`,
    `Elderly Japanese men`,
    `Electricity`,
    `Embryonic stem cells`,
    `Emerging from the sea and rampaging through Tokyo`,
    `Emma Watson`,
    `Emotions`,
    `England`,
    `Erectile dysfunction`,
    `Establishing dominance`,
    `Estrogen`,
    `Ethnic cleansing`,
    `Eugenics`,
    `Euphoria™ by Calvin Klein`,
    `Exactly what you'd expect`,
    `Excalibur`,
    `Exchanging pleasantries`,
    `Executing a hostage every hour`,
    `Existentialists`,
    `Existing`,
    `Expecting a burp and vomiting on the floor`,
    `Explaining how vaginas work`,
    `Explosions`,
    `Extremely tight jeans`,
    `Extremely tight pants`,
    `Extremely tight trousers`,
    `Facebook`,
    `Fading away into nothingness`,
    `Faffing about`,
    `Faith healing`,
    `Fake tits`,
    `FALCON PUNCH!!!`,
    `Famine`,
    `Fancy Feast®`,
    `Farting and walking away`,
    `Farting into your petticoats and wafting it at Lord Gregory`,
    `Fear itself`,
    `Feeding Rosie O'Donnell`,
    `Fellowship in Christ`,
    `Fiery poops`,
    `Fiery poos`,
    `Figgy pudding`,
    `Filling my briefcase with business stuff`,
    `Filling my son with spaghetti`,
    `Filling Sean Hannity with helium and watching him float away`,
    `Finger painting`,
    `Fingering`,
    `Firing a rifle into the air while balls deep in a squealing hog`,
    `Fisting`,
    `Five litres of Special Brew`,
    `Five-Dollar Footlongs™`,
    `Flash flooding`,
    `Flat out not giving a shit`,
    `Flavored condoms`,
    `Flesh-eating bacteria`,
    `Flightless birds`,
    `Flying robots that kill people`,
    `Flying sex snakes`,
    `Forced sterilisation`,
    `Forced sterilization`,
    `Foreskin`,
    `Forgetting the Alamo`,
    `Former President George W Bush`,
    `Four Loko`,
    `Fox News`,
    `Fragile masculinity`,
    `Free samples`,
    `Friction`,
    `Friendly fire`,
    `Friends who eat all the snacks`,
    `Friends who eat all your snacks`,
    `Friends with benefits`,
    `Frolicking`,
    `Front butt`,
    `Fucking my sister`,
    `Fucking the weatherman on live television`,
    `Full frontal nudity`,
    `Funky fresh rhymes`,
    `Gandalf`,
    `Gandhi`,
    `Garth Brooks`,
    `Gary Coleman`,
    `Gary Glitter`,
    `Gay aliens`,
    `Gay conversion therapy`,
    `Geese`,
    `Genetically engineered super-soldiers`,
    `Genghis Khan`,
    `Genital piercings`,
    `Gentleman's Relish®`,
    `Genuine human connection`,
    `German Chancellor Angela Merkel`,
    `German dungeon porn`,
    `Germans on holiday`,
    `Getting a DUI on a Zamboni`,
    `Getting crushed by a vending machine`,
    `Getting cummed on`,
    `Getting drugs off the street and into my body`,
    `Getting drunk on mouthwash`,
    `Getting fingered`,
    `Getting into a pretty bad car accident`,
    `Getting married, having a few kids, buying some stuff, retiring to Florida, and dying`,
    `Getting married, having a few kids, buying some stuff, retiring to Queensland, and dying`,
    `Getting married, having a few kids, buying some stuff, retiring to the south of France, and dying`,
    `Getting naked and watching CBeebies`,
    `Getting naked and watching Nickelodeon`,
    `Getting naked and watching Play School`,
    `Getting pregnant again`,
    `Getting really high`,
    `Getting so angry that you pop a boner`,
    `Getting so angry that you pop a stiffy`,
    `Getting the same Boots Meal Deal every day for six years`,
    `Getting wed, having a few kids, taking some pictures, retiring to the south of France, and dying`,
    `Ghosts`,
    `Girls who shouldn't go wild`,
    `Girls`,
    `Giving 110%`,
    `Giving birth to the Antichrist`,
    `Gladiatorial combat`,
    `Glassing a wanker`,
    `Glenn Beck being harried by a swarm of buzzards`,
    `Glenn Beck catching his scrotum on a curtain hook`,
    `Glenn Beck convulsively vomiting as a brood of crab spiders hatches in his brain and erupts from his tear ducts`,
    `Glenn Beck`,
    `Global warming`,
    `Gloryholes`,
    `Goats eating cans`,
    `Goblins`,
    `God`,
    `GoGurt®`,
    `Going an entire day without masturbating`,
    `Going around punching people`,
    `Golden showers`,
    `Good-natured, fun-loving Aussie racism`,
    `Grandma`,
    `Grandpa's ashes`,
    `Graphic violence, adult language, and some sexual content`,
    `Grave robbing`,
    `Growing a pair`,
    `Guys who don't call`,
    `Haggis`,
    `Half a kilo of pure China White heroin`,
    `Half-assed foreplay`,
    `Harry Potter erotica`,
    `Have some more kugel`,
    `Having a Golden Gaytime`,
    `Having a penis`,
    `Having a shag in the back of a ute`,
    `Having anuses for eyes`,
    `Having big dreams but no realistic way to achieve them`,
    `Having sex for the first time`,
    `Having sex on top of a pizza`,
    `Having sex with every man in Winnipeg`,
    `Having shotguns for legs`,
    `Heartwarming orphans`,
    `Heath Ledger`,
    `Helplessly giggling at the mention of Hutus and Tutsis`,
    `Her Majesty, Queen Elizabeth II`,
    `Her Royal Highness, Queen Elizabeth II`,
    `Heritage minutes`,
    `Heritage minutes`,
    `Heroin`,
    `Heteronormativity`,
    `Hillary Clinton's emails`,
    `Hip hop jewels`,
    `Hipsters`,
    `Historically black colleges`,
    `Hobos`,
    `Holding down a child and farting all over him`,
    `Home video of Oprah sobbing into a Lean Cuisine®`,
    `Homeless people`,
    `Homo milk`,
    `Hooning`,
    `Hope`,
    `Hormone injections`,
    `Horrifying laser hair removal accidents`,
    `Horse meat`,
    `Hospice care`,
    `Hot cheese`,
    `Hot people`,
    `Hot Pockets®`,
    `How amazing it is to be on mushrooms`,
    `How awesome it is to be white`,
    `How bad my daughter fucked up her dance recital`,
    `How far I can get my own penis up my butt`,
    `How wet my pussy is`,
    `However much weed $20 can buy`,
    `However much weed £20 can buy`,
    `Huffing spray paint`,
    `Huge biceps`,
    `Hulk Hogan`,
    `Hunting "accidents"`,
    `Hunting accidents`,
    `Hurling one's body down a hill in pursuit of a wheel of cheese`,
    `Hurricane Katrina`,
    `Hurting those closest to me`,
    `I'm friends with your dad on Facebook`,
    `Ice`,
    `Illegal immigrants`,
    `Impotence`,
    `Improvised explosive devices`,
    `Inappropriate yodeling`,
    `Incest`,
    `Indescribable loneliness`,
    `Inserting a jam jar into my anus`,
    `Inserting a Mason jar into my anus`,
    `Intelligent design`,
    `Intimacy problems`,
    `Invading Poland`,
    `Irritable Bowel Syndrome`,
    `Italians`,
    `Itchy pussy`,
    `JD Power and his associates`,
    `Jade Goody's cancerous remains`,
    `James fucking Cordon`,
    `Jedward`,
    `Jehovah's Witnesses`,
    `Jennifer Lawrence`,
    `Jerking off into a pool of children's tears`,
    `Jesus`,
    `Jew-fros`,
    `Jewish fraternities`,
    `Jews, gypsies, and homosexuals`,
    `Jibber-jabber`,
    `Jimmy Savile`,
    `Jobs`,
    `Joe Biden`,
    `John Howard's eyebrows`,
    `John Wilkes Booth`,
    `Judge Judy`,
    `Judging everyone`,
    `Just touching David Beckham's hair`,
    `Justin Bieber`,
    `Justin Trudeau`,
    `Juuling`,
    `Kamikaze pilots`,
    `Kanye West`,
    `Keanu Reeves`,
    `Keeping Christ in Christmas`,
    `Keg stands`,
    `Kibbles 'n Bits™`,
    `Kibbles n' Bits`,
    `Kids with ass cancer`,
    `Kids with bum cancer`,
    `Kim Jong-il`,
    `Kim Jong-un`,
    `Kissing grandma on the forehead and turning off her life support`,
    `Kissing nan on the forehead and turning off her life support`,
    `Knife crime`,
    `Kourtney, Kim, Khloe, Kendall, and Kylie`,
    `Lactation`,
    `Lads`,
    `Lady Gaga`,
    `Lance Armstrong's missing testicle`,
    `Land mines`,
    `Laying an egg`,
    `Leaked footage of Kate Middleton's colonoscopy`,
    `Leaving an awkward voicemail`,
    `Lena Dunham`,
    `Leprosy`,
    `Letting everyone down`,
    `Letting yourself go`,
    `Leveling up`,
    `Liberals`,
    `Licking the Queen`,
    `Licking things to claim them as your own`,
    `Listening to her problems without trying to solve them`,
    `Literally eating shit`,
    `Little boy penises`,
    `Living in a trash can`,
    `Living in Yellowknife`,
    `Lockjaw`,
    `Loki, the trickster god`,
    `Looking in the mirror, applying lipstick, and whispering "tonight, you will have sex with Tom Cruise"`,
    `Loose lips`,
    `Lumberjack fantasies`,
    `Lunchables™`,
    `LYNX® Body Spray`,
    `Mad cow disease`,
    `Madeleine McCann`,
    `Magnets`,
    `Making a friend`,
    `Making a pouty face`,
    `Making sex at her`,
    `Making the penises kiss`,
    `Making up for centuries of oppression with one day of apologising`,
    `Man meat`,
    `Mansplaining`,
    `Many bats`,
    `Marky Mark and the Funky Bunch`,
    `Martha Stewart`,
    `Martin Lewis, Money Saving Expert`,
    `Massive, widespread drought`,
    `Masturbating`,
    `Masturbation`,
    `Mathletes`,
    `Maureen of Blackpool, Reader's Wife of the Year 1988`,
    `Me time`,
    `Me`,
    `MechaHitler`,
    `Memes`,
    `Men discussing their feelings in an emotionally healthy way`,
    `Men`,
    `Menstrual rage`,
    `Menstruation`,
    `Meth`,
    `Michael Jackson`,
    `Michelle Obama's arms`,
    `Mike Pence`,
    `Mild autism`,
    `Miley Cyrus at 55`,
    `Miley Cyrus`,
    `Millions of cane toads`,
    `Millwall fans`,
    `Mining accidents`,
    `Mistaking a retarded person for someone who's merely deaf`,
    `Mom`,
    `Mooing`,
    `Moral ambiguity`,
    `More elephant cock than I bargained for`,
    `Morgan Freeman's voice`,
    `Mountain Dew Code Red`,
    `Mouth herpes`,
    `Mr Clean, right behind you`,
    `Mr Dressup`,
    `Mr Dressup`,
    `Mr Snuffleupagus`,
    `Mr Squiggle, the Man from the Moon`,
    `Muhammad (Peace Be Upon Him)`,
    `Muhammad (Praise Be Unto Him)`,
    `Multiple orgasms`,
    `Multiple stab wounds`,
    `Murder`,
    `Mutually assured destruction`,
    `Mutually-assured destruction`,
    `Muzzy`,
    `My abusive boyfriend who really isn't so bad once you get to know him`,
    `My balls on your face`,
    `My black ass`,
    `My bright pink fuckhole`,
    `My cheating prick of a husband`,
    `My cheating son-of-a-bitch husband`,
    `My collection of high-tech sex toys`,
    `My collection of Japanese sex toys`,
    `My ex-wife`,
    `My fat daughter`,
    `My father, who died when I was seven`,
    `My first kill`,
    `My genitals`,
    `My good bra`,
    `My humps`,
    `My inner demons`,
    `My little boner`,
    `My machete`,
    `My mate Dave`,
    `My neck, my back, my pussy, and my crack`,
    `My relationship status`,
    `My sex life`,
    `My soul`,
    `My Uber driver, Ajay`,
    `My Uber driver, Pavel`,
    `My ugly face and bad personality`,
    `My vagina`,
    `Nachos for the table`,
    `Naked News`,
    `Natalie Portman`,
    `Natural male enhancement`,
    `Natural selection`,
    `Nazis`,
    `NBA superstar LeBron James`,
    `Necrophilia`,
    `New Age music`,
    `Newfies`,
    `Newfies`,
    `Nickelback`,
    `Nicki Minaj`,
    `Nicolas Cage`,
    `Nip slips`,
    `Nippers`,
    `Nipple blades`,
    `Nocturnal emissions`,
    `Not contributing to society in any meaningful way`,
    `Not giving a shit about the Third World`,
    `Not having sex`,
    `Not reciprocating oral sex`,
    `Not vaccinating my children because I am stupid`,
    `Not wearing pants`,
    `Not wearing trousers`,
    `Nothing but sand`,
    `Nothing`,
    `Nunchuck moves`,
    `Obesity`,
    `Object permanence`,
    `Oestrogen`,
    `Old-people smell`,
    `Ominous background music`,
    `One Direction's supple, hairless bodies`,
    `One Ring to rule them all`,
    `One titty hanging out`,
    `One trillion dollars`,
    `Only dating Asian women`,
    `Oompa-Loompas`,
    `Opposable thumbs`,
    `Oprah`,
    `Our first chimpanzee President`,
    `Our first chimpanzee Prime Minister`,
    `Overcompensation`,
    `Overpowering your father`,
    `Oversized lollipops`,
    `Owning and operating a Chili's franchise`,
    `Pabst Blue Ribbon`,
    `Pac-Man uncontrollably guzzling cum`,
    `Paedophiles`,
    `Panda sex`,
    `Paris Hilton`,
    `Parting the Red Sea`,
    `Party poopers`,
    `Passable transvestites`,
    `Passing a kidney stone`,
    `Passive-aggression`,
    `Passive-aggressive Post-it notes`,
    `Pauline Hanson`,
    `PCP`,
    `Peanut Butter Jelly Time`,
    `Pedophiles`,
    `Peeing a little bit`,
    `Penis breath`,
    `Penis envy`,
    `People who smell their own socks`,
    `Perfunctory foreplay`,
    `Permanent Orgasm-Face Disorder`,
    `Picking up girls at the abortion clinic`,
    `Pictures of boobs`,
    `Pikies`,
    `Pingers`,
    `Pixelated bukkake`,
    `Playing silly buggers`,
    `Police brutality`,
    `Polish People`,
    `Pooping back and forth Forever`,
    `Pooping in a laptop and closing it`,
    `Pooping in the soup`,
    `Poopy diapers`,
    `Poor life choices`,
    `Poor people`,
    `Poorly-timed Holocaust jokes`,
    `Popped collars`,
    `Porn stars`,
    `Poutine`,
    `Poverty`,
    `Power`,
    `Powerful thighs`,
    `Prancing`,
    `Praying the gay away`,
    `Prescription pain killers`,
    `Preteens`,
    `Pretending to care`,
    `Profound respect and appreciation for indigenous culture`,
    `Pronouncing the names of northern Welsh towns`,
    `Prosti-tots`,
    `Pterodactyl eggs`,
    `PTSD`,
    `Puberty`,
    `Public ridicule`,
    `Pulling out`,
    `Pumping out a baby every nine months`,
    `Punching a congressman in the face`,
    `Punching an MP in the face`,
    `Puppies!`,
    `Pussy Galore`,
    `Putting things where they go`,
    `Queefing`,
    `Queen Elizabeth's immaculate anus`,
    `Queuing`,
    `Racially-biased SAT questions`,
    `Racism`,
    `Radical Islamic terrorism`,
    `Rap music`,
    `Raping and pillaging`,
    `Raptor attacks`,
    `Re-gifting`,
    `Rectangles`,
    `Rehab`,
    `Repression`,
    `Republicans`,
    `Reverse cowgirl`,
    `Rich people`,
    `Riding off into the sunset`,
    `Ring Pops`,
    `Ring Pops™`,
    `Rip Torn dropkicking anti-Semitic lesbians`,
    `Ripping off the Beatles`,
    `Ripping open a man’s chest and pulling out his still-beating heart`,
    `Rising from the grave`,
    `Road head`,
    `Rob Ford`,
    `Robbing a sperm bank`,
    `Robert Downey Jr`,
    `Robert Downey, Jr`,
    `RoboCop`,
    `Rohypnol`,
    `Ronald Reagan`,
    `Roofies`,
    `Rubbing Boris Johnson's belly until he falls asleep`,
    `Running naked through a mall, pissing and shitting everywhere`,
    `Running out of semen`,
    `Rupert Murdoch`,
    `Rush Limbaugh's soft, shitty body`,
    `Ruth Bader Ginsburg brutally gaveling your penis`,
    `Ryan Gosling riding in on a white horse`,
    `Ryanair`,
    `Same-sex ice dancing`,
    `Samuel L Jackson`,
    `Santa Claus`,
    `Sarah Palin`,
    `Saxophone solos`,
    `Saying "I love you"`,
    `Scalping the Milkybar Kid`,
    `Scalping`,
    `Schmirler the Curler`,
    `Science`,
    `Scientology`,
    `Scottish independence`,
    `Scousers`,
    `Screaming like a maniac`,
    `Scrotum tickling`,
    `Scrubbing under the folds`,
    `Sean Connery`,
    `Sean Penn`,
    `Seduction`,
    `Seeing Grandma naked`,
    `Seeing Granny naked`,
    `Seeing my father cry`,
    `Seeing what happens when you lock people in a room with hungry seagulls`,
    `Seething with quiet resentment`,
    `Self-flagellation`,
    `Self-loathing`,
    `Selling crack to children`,
    `Selling ice to children`,
    `Seppuku`,
    `Serfdom`,
    `Seven dead and three in critical condition`,
    `Sex with animals`,
    `Sex with Patrick Stewart`,
    `Sexting`,
    `Sexual humiliation`,
    `Sexual peeing`,
    `Sexual tension`,
    `Sexy pillow fights`,
    `Shaking a baby until it stops crying`,
    `Shapeshifters`,
    `Shaquille O'Neal's acting career`,
    `Sharing needles`,
    `Shiny objects`,
    `Shipping convicts to Australia`,
    `Shitting out a perfect Cumberland sausage`,
    `Shitting out a screaming face`,
    `Shorties and blunts`,
    `Showing up to an orgy for the food`,
    `Shutting the fuck up`,
    `Shutting up so I can watch the game`,
    `Shutting up so I can watch the match`,
    `Sideboob`,
    `Silence`,
    `Sipping artificial popcorn butter`,
    `Sitting in a jar of vinegar all night because I am gherkin`,
    `Sitting on my face and telling me I'm garbage`,
    `Sitting on my face`,
    `Sitting on my face`,
    `Skeletor`,
    `Skippy the Bush Kangaroo`,
    `Slapping a biscuit out of an orphan's mouth`,
    `Slapping a racist old lady`,
    `Slapping Nigel Farage over and over`,
    `Slapping your knees to signal your imminent departure`,
    `Slaughtering innocent civilians`,
    `Slavs`,
    `Smallpox blankets`,
    `Smegma`,
    `Sneezing, farting, and cumming at the same time`,
    `Sniffing and kissing my feet`,
    `Sniffing glue`,
    `Snotsicles`,
    `Sobbing into a Hungry-Man™ Frozen Dinner`,
    `Soft, kissy missionary sex`,
    `Soiling oneself`,
    `Solving problems with violence`,
    `Somali pirates`,
    `Some bloody peace and quiet`,
    `Some douche with an acoustic guitar`,
    `Some foundation, mascara, and a touch of blush`,
    `Some god damn peace and quiet`,
    `Some guy`,
    `Some kind of bird man`,
    `Some of the best rappers in the game`,
    `Some punk kid who stole my turkey sandwich`,
    `Some really fucked-up shit`,
    `Sorry, this content cannot be viewed in your region`,
    `Soup that is too hot`,
    `Spaghetti? Again?`,
    `Spaniards`,
    `Spectacular abs`,
    `Spending lots of money`,
    `Sperm whales`,
    `Spirit Airlines`,
    `Spontaneous human combustion`,
    `Stalin`,
    `Staring at a painting and going "hmmmmmmm"`,
    `Stephen Harper`,
    `Stephen Harper`,
    `Stephen Hawking talking dirty`,
    `Steve Bannon`,
    `Steve Irwin`,
    `Stifling a giggle at the mention of Hutus and Tutsis`,
    `Still being a virgin`,
    `Stockholm Syndrome`,
    `Stormtroopers`,
    `Stranger danger`,
    `Strong female characters`,
    `Stunt doubles`,
    `Substitute teachers`,
    `Sucking some dicks to not get drafted`,
    `Sudden Poop Explosion Disease`,
    `Suicidal thoughts`,
    `Summoning Harold Holt from the sea in a time of great need`,
    `Sunshine and rainbows`,
    `Surprise sex!`,
    `Swag`,
    `Sweet, sweet vengeance`,
    `Switching to Geico®`,
    `Swooping`,
    `Synergistic management solutions`,
    `Syrupy sex with a maple tree`,
    `Take-backsies`,
    `Taking a man's eyes and balls out and putting his eyes where his balls go and then his balls in the eye holes`,
    `Taking a sheep-wife`,
    `Taking off your shirt`,
    `Tangled Slinkys`,
    `Tap dancing like there's no tomorrow`,
    `Tasteful sideboob`,
    `Teaching a robot to love`,
    `Team building exercises`,
    `Team-building exercises`,
    `Tearing that ass up like wrapping paper on Christmas morning`,
    `Teenage pregnancy`,
    `Telling a shitty story that goes nowhere`,
    `Tentacle porn`,
    `Terrorists`,
    `Terry Fox's prosthetic leg`,
    `Testicular torsion`,
    `That ass`,
    `That one gay Teletubby`,
    `That thing that electrocutes your abs`,
    `The American Dream`,
    `The Amish`,
    `The arrival of the pizza`,
    `The art of seduction`,
    `The baby that ruined my pussy`,
    `The Bachelorette season finale`,
    `The bastard seagull who stole my chips`,
    `The Big Bang`,
    `The big fucking hole in the ozone layer`,
    `The Black Death`,
    `The Blood of Christ`,
    `The bloody Welsh`,
    `The BNP`,
    `The bombing of Nagasaki`,
    `The boners of the elderly`,
    `The Boy Scouts of America`,
    `The bush`,
    `The Care Bear Stare`,
    `The Chinese gymnastics team`,
    `The chronic`,
    `The clitoris`,
    `The cool, refreshing taste of Coca-Cola®`,
    `The cool, refreshing taste of Pepsi`,
    `The cool, refreshing taste of Pepsi®`,
    `The crazy, ball-slapping sex your parents are having right now`,
    `The Daily Mail`,
    `The Dalai Lama`,
    `The Dance of the Sugar Plum Fairy`,
    `The deformed`,
    `The Devil Himself`,
    `The Donald Trump Seal of Approval™`,
    `The drama club`,
    `The economy`,
    `The EDL`,
    `The end of days`,
    `The entire cast of Downton Abbey`,
    `The entire Internet`,
    `The entire Mormon Tabernacle Choir`,
    `The female orgasm`,
    `The FLQ`,
    `The flute`,
    `The folly of man`,
    `The forbidden fruit`,
    `The Force`,
    `The French`,
    `The gays`,
    `The glass ceiling`,
    `The Great Depression`,
    `The Great Emu War`,
    `The Gulags`,
    `The guys from Queer Eye`,
    `The guys from Queer Eye`,
    `The Hamburglar`,
    `The hardworking Mexican`,
    `The heart of a child`,
    `The Hemsworth brothers`,
    `The hiccups`,
    `The Hillsborough Disaster`,
    `The Holy Bible`,
    `The homosexual agenda`,
    `The homosexual lifestyle`,
    `The Honey Monster`,
    `The human body`,
    `The Hustle`,
    `The illusion of choice in a late-stage capitalist society`,
    `The inevitable heat death of the universe`,
    `The invisible hand`,
    `The Jews`,
    `The KKK`,
    `The Kool-Aid Man`,
    `The land of chocolate`,
    `The light of a billion suns`,
    `The Little Engine That Could`,
    `The magic of live theatre`,
    `The Make-A-Wish Foundation`,
    `The Make-A-Wish® Foundation`,
    `The milk man`,
    `The milkman`,
    `The miracle of childbirth`,
    `The morbidly obese`,
    `The North`,
    `The Official Languages Act La Loi sur les langues officielles`,
    `The only gay person in a hundred kilometers`,
    `The only gay person in a hundred miles`,
    `The opioid epidemic`,
    `The past`,
    `The Patriarchy`,
    `The penny whistle solo from "My Heart Will Go On"`,
    `The People's Elbow`,
    `The petty troubles of the aristrocracy`,
    `The petty troubles of the landed gentry`,
    `The pirate's life`,
    `The placenta`,
    `The plot of a Michael Bay movie`,
    `The Pope`,
    `The profoundly handicapped`,
    `The prunes I've been saving for you in my armpits`,
    `The Rapture`,
    `The Red Hot Chili Peppers`,
    `The Red Menace`,
    `The Rev Dr Martin Luther King, Jr`,
    `The rhythms of Africa`,
    `The Royal Canadian Mounted Police`,
    `The Russians`,
    `The Scouts`,
    `The screamsthe terrible screams`,
    `The Smell of a Primark`,
    `The Smell of Primark`,
    `The South`,
    `The Stig`,
    `The Strictly Come Dancing final`,
    `The Strictly Come Dancing season finale`,
    `The sudden appearance of the Go Compare man`,
    `The Superdome`,
    `The taint; the grundle; the fleshy fun-bridge`,
    `The Tempur-Pedic® Swedish Sleep System™`,
    `The terrorists`,
    `The Thong Song`,
    `The Three-Fifths compromise`,
    `The Three-Fifths Compromise`,
    `The token minority`,
    `The total collapse of the global financial system`,
    `The Trail of Tears`,
    `The true meaning of Christmas`,
    `The Übermensch`,
    `The Underground Railroad`,
    `The unstoppable tide of Islam`,
    `The violation of our most basic human rights`,
    `The Virginia Tech Massacre`,
    `The way James Bond treats women`,
    `The Welsh`,
    `The White Australia Policy`,
    `The wifi password`,
    `The wonders of the Orient`,
    `The World of Warcraft`,
    `The wrath of Vladimir Putin`,
    `Therapy`,
    `Theresa May`,
    `These hoes`,
    `Third base`,
    `This answer is postmodern`,
    `This month's mass shooting`,
    `This year's mass shooting`,
    `Those times when you get sand in your vagina`,
    `Three dicks at the same time`,
    `Throwing a virgin into a volcano`,
    `Throwing grapes at a man until he loses touch with reality`,
    `Tickle Me Elmo`,
    `Tickle Me Elmo™`,
    `Tickling Sean Hannity, even after he tells you to stop`,
    `Tiger Woods`,
    `Tiny nipples`,
    `Tom Cruise`,
    `Tongue`,
    `Toni Morrison's vagina`,
    `Tony Abbott in budgie smugglers`,
    `Too much hair gel`,
    `Tories`,
    `Total control of the media`,
    `Touching a pug right on his penis`,
    `Trench foot`,
    `Tripping balls`,
    `Tweeting`,
    `Twenty tonnes of bat shit`,
    `Twinkies®`,
    `Two midgets shitting into a bucket`,
    `Unfathomable stupidity`,
    `Uppercuts`,
    `Used knickers`,
    `Used panties`,
    `Vegemite™`,
    `Vehicular homicide`,
    `Vehicular manslaughter`,
    `Viagra®`,
    `Vigilante justice`,
    `Vigorous jazz hands`,
    `Vikings`,
    `Vladimir Putin`,
    `Vomiting into a kangaroo's pouch`,
    `Vomiting mid-blowjob`,
    `Vomiting seafood and bleeding anally`,
    `Waiting 'til marriage`,
    `Waiting till marriage`,
    `Waking up half-naked in a Denny's parking lot`,
    `Waking up half-naked in a Little Chef car park`,
    `Waking up half-naked in a Macca's car park`,
    `Waking up half-naked in a Wetherspoons car park`,
    `Waking up in Idris Elba's arms`,
    `Walking in on Dad peeing into Mom's mouth`,
    `Wanking into a pool of children's tears`,
    `Waterboarding`,
    `Weapons-grade plutonium`,
    `Wearing an octopus for a hat`,
    `Wearing underwear inside out to avoid doing laundry`,
    `Wearing underwear inside-out to avoid doing laundry`,
    `Wet dreams`,
    `What that mouth do`,
    `What's left of the Great Barrier Reef`,
    `When you fart and a little bit comes out`,
    `Whining like a little bitch`,
    `Whipping it out`,
    `Whiskas® Catmilk`,
    `White people`,
    `White power`,
    `White power`,
    `White privilege`,
    `White-man scalps`,
    `Whoever the Prime Minister is these days`,
    `Wifely duties`,
    `Will Smith`,
    `William Shatner`,
    `Winking at old people`,
    `Wiping her bum`,
    `Wiping her butt`,
    `Wizard music`,
    `Women in yoghurt adverts`,
    `Women in yoghurt commercials`,
    `Women in yogurt commercials`,
    `Women of color`,
    `Women of colour`,
    `Women voting`,
    `Women's suffrage`,
    `Women's undies`,
    `Wondering if it's possible to get some of that salsa to go`,
    `Words`,
    `World peace`,
    `Worshipping that pussy`,
    `Xenophobia`,
    `Yeast`,
    `YOU MUST CONSTRUCT ADDITIONAL PYLONS`,
    `Your mum`,
    `Your weird brother`,
    `A narc`,
    `A sorry excuse for a father`,
    `A supportive touch on the lower back`,
    `Backing over a kid with the Buick`,
    `Black Jesus`,
    `Burgers and pussy`,
    `Climbing a telephone pole and becoming one with the T-Mobile network`,
    `COVID-19`,
    `Crab`,
    `Explaining the difference between sex and gender`,
    `Grabbing my man by his love handles and fucking his big ass`,
    `Having a stroke`,
    `Kayaking with my sluts`,
    `My Black ass`,
    `My boss`,
    `Our dildo`,
    `Pissing in my thirsty mouth`,
    `The prostate`,
    `Your mom`,
]

//Apples to Apples card set (Family Friendly)
//Credit: http://www.com-www.com/applestoapples/applestoapples-partyset-green-2004.html

const promptApples = [
    'Absurd',
    'Addictive',
    'Adorable',
    'Aged',
    'American',
    'Ancient',
    'Animated',
    'Annoying',
    'Appetizing',
    'Arrogant',
    'Awesome',
    'Awkward',
    'Believable',
    'Bogus',
    'Boisterous',
    'Bold',
    'Boring',
    'Bright',
    'Brilliant',
    'Busy',
    'Calm',
    'Casual',
    'Charismatic',
    'Charming',
    'Cheesy',
    'Chewy',
    'Chunky',
    'Classic',
    'Clean',
    'Clueless',
    'Cold',
    'Colorful',
    'Comfortable',
    'Comical',
    'Complicated',
    'Confused',
    'Cool',
    'Corrupt',
    'Cosmic',
    'Cosmopolitan',
    'Courageous',
    'Cowardly',
    'Cranky',
    'Crazed',
    'Crazy',
    'Creative',
    'Creepy',
    'Cruel',
    'Cuddly',
    'Cute',
    'Dainty',
    'Dangerous',
    'Dead',
    'Deadly',
    'Delicate',
    'Delicious',
    'Delightful',
    'Demanding',
    'Depressing',
    'Desperate',
    'Dignified',
    'Dirty',
    'Distinguished',
    'Disturbing',
    'Dramatic',
    'Dreamy',
    'Dull',
    'Dysfunctional',
    'Earthy',
    'Easy',
    'Eccentric',
    'Elitist',
    'Emotional',
    'Eternal',
    'European',
    'Exciting',
    'Exhausting',
    'Expensive',
    'Explosive',
    'Exquisite',
    'Extreme',
    'Fabulous',
    'Fake',
    'Fancy',
    'Fantastic',
    'Feminine',
    'Filthy',
    'Flirtatious',
    'Foreign',
    'Fragrant',
    'Frazzled',
    'Fresh',
    'Friendly',
    'Frightening',
    'Frivolous',
    'Funky',
    'Funny',
    'Furious',
    'Fuzzy',
    'Glamorous',
    'Glitzy',
    'Global',
    'Glorious',
    'Good-Goody',
    'Graceful',
    'Handsome',
    'Hardworking',
    'Harmful',
    'Haunting',
    'Healthy',
    'Heartless',
    'Hilarious',
    'Honorable',
    'Hopeless',
    'Horrifying',
    'Hostile',
    'Hot',
    'Idiotic',
    'Important',
    'Industrious',
    'Influential',
    'Innocent',
    'Insane',
    'Inspirational',
    'Insulting',
    'Intelligent',
    'Intense',
    'Irresistible',
    'Irritating',
    'Juicy',
    'Lazy',
    'Legendary',
    'Loud',
    'Lovable',
    'Lucky',
    'Luscious',
    'Luxurious',
    'Magical',
    'Manly',
    'Masculine',
    'Meek',
    'Melodramatic',
    'Mischievous',
    'Miserable',
    'Misunderstood',
    'Mysterious',
    'Mystical',
    'Naive',
    'Nasty',
    'Natural',
    'Neat',
    'Neglected',
    'Nerdy',
    'Normal',
    'Obnoxious',
    'Odd',
    'Offensive',
    'Ordinary',
    'Organic',
    'Outrageous',
    'Overwhelming',
    'Painful',
    'Pathetic',
    'Patriotic',
    'Peaceful',
    'Perfect',
    'Philosophical',
    'Phony',
    'Playful',
    'Popular',
    'Powerful',
    'Primitive',
    'Principled',
    'Profound',
    'Puffy',
    'Pure',
    'Quiet',
    'Radiant',
    'Radical',
    'Rare',
    'Realistic',
    'Refined',
    'Refreshing',
    'Relaxing',
    'Repulsive',
    'Responsible',
    'Revolutionary',
    'Rich',
    'Ridiculous',
    'Risky',
    'Rough',
    'Saintly',
    'Sappy',
    'Scary',
    'Scenic',
    'Selfish',
    'Senseless',
    'Sensitive',
    'Sensual',
    'Sexy',
    'Shallow',
    'Sharp',
    'Shiny',
    'Shocking',
    'Shy',
    'Silly',
    'Smart',
    'Smelly',
    'Smooth',
    'Snappy',
    'Soft',
    'Speedy',
    'Spicy',
    'Spiritual',
    'Spooky',
    'Spunky',
    'Squeaky Clean',
    'Stereotyped',
    'Stunning',
    'Sultry',
    'Sweet',
    'Swift',
    'Talented',
    'Tame',
    'Technological',
    'Temperamental',
    'Timeless',
    'Touchy-Feely',
    'Tough',
    'Trustworthy',
    'Twisted',
    'Unbelievable',
    'Unforgettable',
    'Unhealthy',
    'Unnatural',
    'Unreal',
    'Unscrupulous',
    'Unusual',
    'Useless',
    'Violent',
    'Virtuous',
    'Visionary',
    'Weird',
    'Wicked',
    'Wild',
    'Witty',
    'Woebegone',
    'Worldly',
    'Zany',
   ]
   
   //credit: http://www.com-www.com/applestoapples/applestoapples-partyset-red-2004.html
   const responseApples = [
    "A Bad Haircut",
    "A Bull Fight",
    "A Car Crash",
    "A Cheap Motel",
    "A Crawl Space ",
    "A Dozen Red Roses",
    "A Flat Tire",
    "A Full Moon",
    "A Haunted House",
    "A High School Bathroom",
    "A Honeymoon",
    "A Locker Room ",
    "A Morgue ",
    "A Nine Iron",
    "A School Bus",
    "A School Cafeteria ",
    "A Sunrise",
    "A Sunset ",
    "A Tree House",
    "A Used Car Lot",
    "Abraham Lincoln ",
    "Adam Sandler",
    "Adolph Hitler ",
    "AIDS",
    "Airline Food",
    "Al Pacino",
    "Albert Einstein ",
    "Alfred Hitchcock",
    "Alien Abductions",
    "Americans",
    "Amputations",
    "Angry Hornets ",
    "Andy Warhol",
    "Anne Frank ",
    "Antarctica",
    "Anthony Hopkins ",
    "Apple Pie",
    "Apples",
    "Armed Robbery ",
    "Assembly Lines",
    "At My Parent's House ",
    "Atlantis ",
    "Atomic Bombs",
    "Attack On Pearl Harbor",
    "Austin Powers ",
    "Australian Outback ",
    "Babe Ruth",
    "Babies",
    "Baby Showers",
    "Backstreet Boys ",
    "Bad Dogs ",
    "Bagpipes ",
    "Baked Beans",
    "Baked Potatoes",
    "Baking Cookies",
    "Bald Eagles",
    "Ballerinas ",
    "Bangkok",
    "Bankruptcy ",
    "Barbara Walters ",
    "Barbed Wire",
    "Barfing",
    "Barney",
    "Bart Simpson",
    "Bates Motel",
    "Batman",
    "Bats",
    "Beach Parties ",
    "Beanie Babies ",
    "Beauty And The Beast ",
    "Beer",
    "Beer Bellies",
    "Beethoven",
    "Beets ",
    "Being In Love",
    "Ben Stiller",
    "Berlin",
    "Big Bang Theory ",
    "Big Macs ",
    "Bigfoot",
    "Bill Clinton",
    "Bill Gates ",
    "Bill Murray",
    "Billboards ",
    "Bingo ",
    "Bird Watching ",
    "Black Holes",
    "Black Velvet",
    "Blizzard ",
    "Blood ",
    "Board Games",
    "Body Odor",
    "Body Piercing ",
    "Body Surfing",
    "Bonbons",
    "Bongos",
    "Bottled Water ",
    "Boxing",
    "Boy Scouts ",
    "Boyfriends ",
    "Brad Pitt",
    "Brain Surgeons",
    "Brains",
    "Britney Spears",
    "Broadway ",
    "Bruce Willis",
    "Bubble Gum ",
    "Bubbles",
    "Bullwinkle ",
    "Bumper Stickers ",
    "Bungee Jumping",
    "Buying A House",
    "Cabbage",
    "Cactus",
    "California ",
    "Camping Trip",
    "Canada",
    "Canadians",
    "Captain Kirk",
    "Car Bombs",
    "Car Horns",
    "Carl Sagan ",
    "Carnival Workers",
    "Cary Grant ",
    "Casablanca ",
    "Casinos",
    "Castles",
    "Caves ",
    "Celine Dion",
    "Cell Phones",
    "Cesar Chavez",
    "Chain Letters ",
    "Chains",
    "Challenger Explosion ",
    "Chameleons ",
    "Charging Rhinos ",
    "Cheesecake ",
    "Cher",
    "Chicago",
    "Chicken Pox",
    "Chickens ",
    "Chimpanzees",
    "China ",
    "Chinatown",
    "Choir Boys ",
    "Chorus Girls",
    "Cigarette Burns ",
    "Cigarettes ",
    "Cinco de Mayo ",
    "Cindy Crawford",
    "Clark Gable",
    "Claude Monet",
    "Cleaning The Bathroom ",
    "Cleopatra",
    "Clint Eastwood",
    "Clowns",
    "Cocaine",
    "Cockroaches",
    "Coconuts ",
    "Cold Pizza ",
    "Communists ",
    "Commuting",
    "Computer Hackers",
    "Computers",
    "Confucius",
    "Conspiracy Theories",
    "Construction Workers ",
    "Corn On The Cob ",
    "Corvettes",
    "Count Dracula ",
    "Country Music",
    "Crazy Horse",
    "Creamed Corn",
    "Crystal Balls ",
    "Cuba",
    "Cults ",
    "Custer's Last Stand",
    "Dandruff ",
    "Danielle Steel",
    "Danny DeVito",
    "Dark Alleys",
    "Darth Vader",
    "Dating",
    "David Letterman ",
    "Daytime TV ",
    "Death Valley",
    "Deer Hunting",
    "Demi Moore ",
    "Democrats",
    "Denzel Washington",
    "Detroit",
    "Diamonds ",
    "Discos",
    "Discovering America",
    "Disneyland ",
    "Divorce",
    "Doctors",
    "Doing The Dishes",
    "Dolly Parton",
    "Dr. Kevorkin",
    "Dr. Seuss",
    "Driving Off A Cliff",
    "Duct Tape",
    "Ear Wax",
    "Earthquakes",
    "Earwigs",
    "East Coast ",
    "Eddie Murphy",
    "Eleanor Roosevelt",
    "Electric Eels ",
    "Electricity",
    "Elephants",
    "Elizabeth Taylor",
    "Elvis Presley ",
    "Emily Dickinson ",
    "Ernest Hemingway",
    "Europe",
    "Exorcism ",
    "Eyes",
    "Falling Down",
    "Family Reunions ",
    "Family Vacations",
    "Family Values ",
    "Fast Food",
    "Feathers ",
    "Feminists",
    "Festering Wounds",
    "Fidel Castro",
    "Firefighters",
    "Firestorms ",
    "Fireworks",
    "First Man On The Moon ",
    "Flipper",
    "Fly Fishing",
    "Flying Monkeys",
    "Forest Fires",
    "Fort Knox",
    "Fourth Of July",
    "Frank Lloyd Wright ",
    "Frank Sinatra ",
    "Freckles ",
    "Freedom",
    "French Wines",
    "Fresh Water Pearls ",
    "Friction ",
    "Fund Raising",
    "Funerals ",
    "Fur ",
    "Fuzz",
    "Gall Bladder",
    "Gang Members",
    "Garrison Keillor",
    "Garth Brooks",
    "Geishas",
    "Gen. George S. Patton ",
    "Genetic Engineering",
    "George W. Bush",
    "George Washington",
    "Georgia O'Keeffe",
    "Getting A Hug ",
    "Ghost Towns",
    "Ghosts",
    "Giant Squid",
    "Gila Monsters ",
    "Gingko Trees",
    "Ginseng",
    "Girl Scouts",
    "Girlfriends",
    "Giving A Hug",
    "Glaciers ",
    "Glazed Donuts ",
    "Global Warming",
    "Going To Church ",
    "Going To Grandma's ",
    "Going To School ",
    "Going To The Dentist ",
    "Going To The Gym",
    "Gold Chains",
    "Goldfish",
    "Grace Kelly",
    "Graffiti ",
    "Grass Skirts",
    "Grave Robbers ",
    "Gravity",
    "Greenpeace ",
    "Gym Teachers",
    "Hair Transplants",
    "Hairballs",
    "Halloween",
    "Hand Grenades ",
    "Handcuffs",
    "Handguns ",
    "Hangnails",
    "Having A Baby ",
    "Having An Operation",
    "Hawaii",
    "Helen Keller",
    "Hiccups",
    "High School Football ",
    "High School Reunions ",
    "Hillary Rodham Clinton",
    "Hiroshima",
    "HMOs",
    "Hockey",
    "Hollywood",
    "Homeless Shelters",
    "Homer Simpson ",
    "Homework ",
    "Hooligans",
    "Horseback Riding",
    "Hot Lava ",
    "House Guests",
    "Hummingbirds",
    "Humphrey Bogart ",
    "Icebergs ",
    "In A Coma",
    "Incense",
    "India ",
    "Indiana Jones ",
    "Industrial Revolution",
    "Infomercials",
    "Inside The Sun",
    "Intellectuals ",
    "Ireland",
    "Israel",
    "Italy ",
    "Jack Nicholson",
    "Jack The Ripper ",
    "Jackie Chan",
    "Jacques Cousteau",
    "Jamaica",
    "James Bond ",
    "James Dean ",
    "Japan ",
    "Japanese ",
    "Jelly Beans",
    "Jennifer Lopez",
    "Jerry Springer",
    "Jesse Jackson ",
    "Jesse Ventura ",
    "Jim Carrey ",
    "Jimmy Stewart",
    "Joan Of Arc",
    "Jodie Foster ",
    "John F. Kennedy ",
    "John Glenn ",
    "John Philip Sousa",
    "John Travolta ",
    "Judge Judy ",
    "Julia Roberts ",
    "Junk Mail",
    "Jupiter",
    "Katherine Hepburn",
    "Keanu Reeves",
    "Killer Whales ",
    "Kilts ",
    "King Arthur",
    "King Henry VIII ",
    "Knoc",
    "Labor Unions",
    "Large Mouth Bass",
    "Las Vegas",
    "Lawyers",
    "Leaf Blowers",
    "Leather",
    "Leeches",
    "Lemons",
    "Lenin's Tomb",
    "Leonardo Da Vinci",
    "Lightning",
    "Loan Sharks",
    "Lobster",
    "Local Police",
    "Log Cabins ",
    "Lollipops",
    "London",
    "Looking For A Job",
    "Los Angeles",
    "Losing Your Job ",
    "Lucille Ball",
    "Machine Guns",
    "Mad Cow Disease ",
    "Madame Curie",
    "Madonna",
    "Magic Tricks",
    "Mahatma Gandhi",
    "Manhattan",
    "Mardi Gras ",
    "Marilyn Monroe",
    "Mark Twain ",
    "Marriage ",
    "Mars",
    "Martha Stewart",
    "Martin Luther King",
    "Meat Cleavers ",
    "Meatloaf ",
    "Meg Ryan ",
    "Mel Gibson ",
    "Men ",
    "Men In Black",
    "Meryl Streep",
    "Mexico",
    "Mice",
    "Michael Jackson ",
    "Michael Jordon",
    "Michelangelo",
    "Michelle Pfeiffer",
    "Microsoft",
    "Midlife Crisis",
    "Mike Tyson ",
    "Miles Davis",
    "Milk",
    "Milk Duds",
    "Mirrors",
    "Mold",
    "Money ",
    "Morticians ",
    "Mosquitoes ",
    "Motorcycles",
    "Mount Rushmore",
    "MTV ",
    "Mud ",
    "Mudslides",
    "Muhammad Ali",
    "Musicals ",
    "My 16th Birthday",
    "My Bank Account ",
    "My Bathroom",
    "My Bedroom ",
    "My Body",
    "My Boss",
    "My Dreams",
    "My Family",
    "My First Kiss ",
    "My Friends ",
    "My Future",
    "My Hair",
    "My High School Prom",
    "My Job",
    "My Love Life",
    "My Mind",
    "My Neighborhood ",
    "My Past",
    "My Personality",
    "My Refrigerator ",
    "Napoleon Bonaparte ",
    "NASCAR",
    "Neil Simon ",
    "New Orleans",
    "New Shoes",
    "New York City ",
    "Niagara Falls ",
    "Nicholas Cage ",
    "Ninjas",
    "Nobel Peace Prize",
    "Noisy Neighbors ",
    "Normal Rockwell ",
    "Nuclear Power Plants ",
    "NYPD",
    "Oil Spills ",
    "Olive Oil",
    "Oprah Winfrey ",
    "Oral Surgery",
    "Oranges",
    "Oxygen",
    "Pablo Picasso ",
    "Parenting",
    "Paris, France ",
    "Paying Bills",
    "Paying Taxes",
    "Penguins ",
    "Picking Your Nose",
    "Pigeons",
    "Pigs",
    "Piranha",
    "Pirates",
    "Pit Bulls",
    "Plane Crashes ",
    "Plastic",
    "Playing Chess ",
    "Poison Ivy ",
    "Pokemon",
    "Pond Scum",
    "Poodles",
    "Popcorn",
    "Porsche Boxster ",
    "Postal Workers",
    "Power Tools",
    "Prince Charming ",
    "Princess Diana",
    "Pro Wrestling ",
    "Psychiatrists ",
    "Psychics ",
    "Public Radio",
    "Puff Daddy ",
    "Pulling Weeds ",
    "Pumping Iron",
    "Pushups",
    "Pyramids ",
    "Quentin Terantino",
    "Quicksand",
    "Ragweed",
    "Rain",
    "Rainbows ",
    "Rappers",
    "Reading A Good Book",
    "Recreational Vehicles ",
    "Recycling",
    "Red Raspberries ",
    "Rednecks ",
    "Redwood Forests ",
    "Reggae Music",
    "Regis Philbin ",
    "Remote Controls ",
    "Republicans",
    "Richard Nixon",
    "Robert DeNiro ",
    "Road Kill",
    "Road Trips ",
    "Robin Williams",
    "Rock And Roll ",
    "Rock Concert",
    "Rocket Scientists",
    "Rocky Mountains ",
    "Rolling The Car ",
    "Roman Numerals",
    "Romeo And Juliet",
    "Root Beer Floats",
    "Rosa Parks ",
    "Rosie O'Donnell ",
    "Rubber Gloves ",
    "Running A Marathon ",
    "Rush Limbaugh ",
    "Russia",
    "Rust",
    "Saddam Hussein",
    "Sailors",
    "Salads",
    "Salsa Dancing ",
    "Salvador Dali ",
    "Samuel L. Jackson",
    "Saturday Cartoons",
    "San Francisco ",
    "Saturn",
    "Scavenger Hunt",
    "Scene Of The Crime ",
    "Schindler's List",
    "Science Fair Projects ",
    "Science Fiction ",
    "Screeching ",
    "Sean Connery",
    "Shania Twain",
    "Sharks",
    "Shopping Mall ",
    "Silk",
    "Silly Putty",
    "Skateboarding ",
    "Skiing",
    "Skinheads",
    "Skunks",
    "Skydiving",
    "Sleeping Pills",
    "Slivers",
    "Sloppy Joes",
    "Smithsonian Institution",
    "Snakes",
    "Snow",
    "Social Security ",
    "Socks ",
    "South Africa",
    "South Park ",
    "Soy Sauce",
    "Spam",
    "Speeding Tickets",
    "Spiders",
    "Spike Lee",
    "Spilled Milk",
    "Spit",
    "Spontaneous Combustion",
    "Sport Utility Vehicles",
    "Sports Channels ",
    "Star Fruit ",
    "Starry Night",
    "State Fair ",
    "Steak And Potatoes",
    "Stephen King",
    "Steve Martin",
    "Steven Spielberg",
    "Stonehenge ",
    "Strawberry Shortcake ",
    "Stubbed Toes",
    "Stunt People",
    "Summer Camp",
    "Sunday Drivers",
    "Superman ",
    "Supermodels",
    "Surfing The Net ",
    "Sushi ",
    "Swiss Bank Accounts",
    "Swiss Chocolate ",
    "Swiss Cheese",
    "Taking A Bath ",
    "Talk Radio ",
    "Teachers ",
    "Telemarketers",
    "Televangelists",
    "Television",
    "Telling The Truth",
    "Terrorist Attack",
    "Thanksgiving Day",
    "The 1920s",
    "The 1950s",
    "The 1960s",
    "The 1970s",
    "The 1980s",
    "The 21st Century",
    "The Academy Awards",
    "The Beach",
    "The Beatles",
    "The CIA",
    "The Cold War",
    "The Common Loon",
    "The Dallas Cowboys",
    "The Dump",
    "The Eiffel Tower",
    "The Electric Chair",
    "The End Of The World",
    "The Everglades",
    "The Far Left",
    "The Far Right",
    "The FBI",
    "The First Day Of School",
    "The French Riviera",
    "The Godfather",
    "The Grand Canyon",
    "The Grateful Dead",
    "The Great Chicago Fire",
    "The Great Depression",
    "The Green Bay Packers",
    "The Gulf War",
    "The Indy 500",
    "The Internet",
    "The IRS",
    "The JFK Assassination",
    "The KKK",
    "The Land Of Oz",
    "The Little Mermaid",
    "The Mafia",
    "The Marx Brothers",
    "The Metric System",
    "The Midwest",
    "The Milky Way",
    "The Mississippi River",
    "The National Enquirer",
    "The New York Yankees",
    "The NRA",
    "The Ocean",
    "The Old Man And The Sea",
    "The Olympics",
    "The Opera",
    "The Ozone Layer",
    "The Pentagon",
    "The Pyramids",
    "The Renaissance",
    "The Rolling Stones",
    "The San Andreas Fault",
    "The South",
    "The Statue Of Liberty",
    "The Super Bowl",
    "The Supreme Court",
    "The Three Tenors",
    "The Titanic",
    "The Universe",
    "The Vatican",
    "The Vietnam Memorial",
    "The Williams Sisters ",
    "The Wright Brothers",
    "The YMCA",
    "Thomas Edison",
    "Thunder",
    "Tibet",
    "Ticks",
    "Tidal Waves",
    "Tiger Woods",
    "Toasted Marshmallows",
    "Toasters",
    "Tobacco Companies",
    "Toes",
    "Tom Cruise",
    "Tom Hanks",
    "Top Of A Rollercoaster",
    "Tornadoes",
    "Toys",
    "Trailer Parks",
    "Trampolines",
    "Tree Huggers",
    "Truck Stops",
    "Tyrannosaurus Rex",
    "Underwear",
    "United Nations",
    "Vacations",
    "Vampires",
    "Victorian England",
    "Video Games",
    "Vietnam, 1968",
    "Vincent Van Gogh",
    "Violins",
    "VW Beetles",
    "Waco, Texas",
    "Wall Street",
    "Walt Disney",
    "Warts",
    "Watching Football",
    "Water Parks",
    "Waterbeds",
    "Waterfalls",
    "Watermelons",
    "Weapons Dealers ",
    "Weddings",
    "Wheat",
    "Wheel Of Fortune",
    "Whipped Cream",
    "Whips",
    "Whoopie Goldberg",
    "Will Smith",
    "William Shakespeare",
    "Wimbledon",
    "Windsurfing",
    "Wine Tasting",
    "Winning The Lottery",
    "Witch Hunts",
    "Women",
    "Women's Soccer",
    "Wood Chippers ",
    "Woodstock",
    "Woody Allen",
    "Worms",
    "X-Ray Vision",
    "X-Rays",
    "Yellowstone Park",
    "Zen",
    "Zucchini",
   ]
   
   